"""initial_schema

Revision ID: bb1b462541d1
Revises: 
Create Date: 2026-08-22 15:56:54.724792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1b462541d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_completeness', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('follow_burst_rate', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('posting_variance', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('engagement_rate', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('recommended_action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'recommended_action')
    op.drop_column('profiles', 'engagement_rate')
    op.drop_column('profiles', 'posting_variance')
    op.drop_column('profiles', 'follow_burst_rate')
    op.drop_column('profiles', 'profile_completeness')
    # ### end Alembic commands ###
